#!/bin/bash

set -eo pipefail

BUCKET_NAME=${BUCKET_NAME:-driving-sim/projects/maliput/packages/nightlies}

# Rename nightly build.
BUNDLE_NAME=${BUNDLE_NAME:-maliput-desktop}
mv install ${BUNDLE_NAME}

# Compress current nightly build.
CURRENT_BUNDLE_TARBALL_NAME="${BUNDLE_NAME}-$(date +%Y%m%d)-bionic.tar.gz"
tar -czvf ${CURRENT_BUNDLE_TARBALL_NAME} ${BUNDLE_NAME}

# Push current nightly build tarball.
aws s3 cp ${CURRENT_BUNDLE_TARBALL_NAME} s3://${BUCKET_NAME}/${CURRENT_BUNDLE_TARBALL_NAME}

# Push and overwrite latest nightly build tarball.
LATEST_BUNDLE_TARBALL_NAME="${BUNDLE_NAME}-latest-bionic.tar.gz"
aws s3 cp s3://${BUCKET_NAME}/${LATEST_BUNDLE_TARBALL_NAME} s3://${BUCKET_NAME}/${LATEST_BUNDLE_TARBALL_NAME}
