#!/bin/bash

set -eo pipefail

JOBS=$(($(getconf _NPROCESSORS_ONLN)/2))

# Address Sanitizer.

MAKEFLAGS="-j${JOBS}" CC=clang CXX=clang++ colcon build \
  --parallel-workers ${JOBS} \
  --cmake-args ' -DCMAKE_LINKER=/usr/bin/llvm-ld' ' -DADDRESS_SANITIZER=On' \
  ${COLCON_BUILD_EXTRA_ARGS:-}

source ./install/setup.bash

colcon test --event-handlers=console_direct+ --return-code-on-test-failure \
       --packages-skip PROJ4 pybind11 ${COLCON_TEST_EXTRA_ARGS:-}
