#!/bin/bash

set -eo pipefail

source ./.bashrc

colcon build --parallel-workers $(($(getconf _NPROCESSORS_ONLN)/2)) \
       --cmake-args ' -DCMAKE_BUILD_TYPE=Release' \
       ${COLCON_BUILD_EXTRA_ARGS:-}
