#!/bin/bash

set -eo pipefail

rosdep update

sudo rosdep install -i -y --rosdistro=$ROS_DISTRO --skip-keys="ignition-transport5 ignition-msgs2 ignition-math6 ignition-common3 ignition-gui0 ignition-rendering2 pylint3 pycodestyle libqt5multimedia5 libboost-filesystem-dev pybind11 PROJ4" --from-paths src
