#!/bin/bash

set -eo pipefail

# We need ssh keys from TRI to access all private repos. Code below fetches them
# from an S3 bucket that TRI has, and is a bash version of the code located
# at: https://github.com/RobotLocomotion/drake-ci/blob/master/driver/configurations/aws.cmake
# and: https://github.com/RobotLocomotion/drake-ci/blob/master/tools/git_ssh.bash.in
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends awscli curl git

SSH_IDENTITY_FILE=$( mktemp /tmp/id_rsa_XXXXXXXX )
aws s3 cp s3://drake-provisioning/id_rsa "$SSH_IDENTITY_FILE"
SSH_IDENTITY_SHA1=$( sha1sum "$SSH_IDENTITY_FILE" | cut -d' ' -f1 )
test "$SSH_IDENTITY_SHA1" = "8de7f79df9eb18344cf0e030d2ae3b658d81263b"
chmod 0400 "$SSH_IDENTITY_FILE"
GIT_SSH_FILE=$( mktemp /tmp/git_ssh_XXXXXXXX )
cat > $GIT_SSH_FILE <<EOF
ssh -i "$SSH_IDENTITY_FILE" -o StrictHostKeyChecking=no "\$@"
EOF
chmod 0755 $GIT_SSH_FILE
export GIT_SSH=$GIT_SSH_FILE

mkdir -p src

vcs import -f src < ./index/maliput.repos

vcs pull src

if [ ! -z "$CHANGE_BRANCH" ]; then
    echo ">>> Merging custom branch $CHANGE_BRANCH into default branches"
    vcs custom src --args branch -f $CHANGE_BRANCH origin/$CHANGE_BRANCH > /dev/null || true
    vcs custom src --args merge --no-edit $CHANGE_BRANCH  > /dev/null || true
    DIFF=\$(vcs diff -s src | tr -d '.\n')
    if [ ! -z "$DIFF" ]; then
        echo "Have merge conflicts!"
        echo $DIFF
        exit 1
    fi
    vcs status src
fi

unset GIT_SSH
rm -f "$GIT_SSH_FILE"
rm -f "$SSH_IDENTITY_FILE"

sudo prereqs-install -t all src
