#!/bin/bash

set -eo pipefail

JOBS=$(($(getconf _NPROCESSORS_ONLN)/2))

./run_scan_build \
  --parallel-workers ${JOBS} \
  --cmake-args -DCMAKE_LINKER=/usr/bin/llvm-ld \
  ${COLCON_BUILD_EXTRA_ARGS:-}
