#!/bin/bash

set -euo pipefail

# The setup_early script installs just the necessary bootstrap dependencies to
# be able to build the workspace.  All other dependencies will be installed
# during setup_late.

export DEBIAN_FRONTEND='noninteractive'

# Install the common dependencies and ignition libraries.
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends awscli curl git
