#!/bin/bash

set -eu

# Here we install the prerequisistes for each source dependency as well as
# drake's. Note that we disable the '-o pipefail' directive above because
# we need to pipe 'yes' into 'install_prereqs.sh' scripts for them to succeed.
# Given that we have no other pipes in this file, this should be safe enough.

export DEBIAN_FRONTEND='noninteractive'

yes | sudo /opt/drake/share/drake/setup/install_prereqs
for script in $(find ./src -name 'install_prereqs.sh'); do
    yes | sudo $script
done
