#!/bin/bash

set -euo pipefail

# The setup_early script installs just the necessary bootstrap dependencies to
# be able to build the workspace.  All other dependencies will be installed
# during setup_late.

sudo ./index/tools/prereqs-install index/

./index/tools/wsetup -v --no-container .
