#!/bin/bash

set -euo pipefail

# The setup_early script installs just the necessary bootstrap dependencies to
# be able to build the workspace.  All other dependencies will be installed
# during setup_late.

export DEBIAN_FRONTEND='noninteractive'
export PREREQS_NONINTERACTIVE=1

./index/tools/prereqs-install -y index/

./index/tools/dsim-wsetup
