#!/bin/bash

set -eo pipefail

JOBS=$(($(getconf _NPROCESSORS_ONLN)/2))

# Thread Sanitizer.
# Only malidrive contains multithreaded code.
if [ "${ENABLE_TSAN}" = "ON" ]
then
  MAKEFLAGS="-j${JOBS}" CC=clang CXX=clang++ colcon build \
    --parallel-workers ${JOBS} \
    --cmake-args ' -DCMAKE_LINKER=/usr/bin/llvm-ld' ' -DTHREAD_SANITIZER=On' \
    --packages-up-to malidrive

  source ./install/setup.bash

  colcon test --event-handlers=console_direct+ --return-code-on-test-failure \
        --packages-select malidrive
fi
