#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $0))
INDEX_PATH=$(realpath $SCRIPT_PATH/..)
SETUP_PATH=$(mktemp /tmp/setup.XXXXXX)

$SCRIPT_PATH/generate_maliput_setup_script --inside-docker maliput-devel \
    --with-drake-nightly $INDEX_PATH/drake.repos --with-stable-ignition \
    --repos $INDEX_PATH/maliput.repos -o $SETUP_PATH

# Execution must be done this way to let signals reach docker.
$SETUP_PATH $@

rm $SETUP_PATH
