name: aws test

on:
  push:
  pull_request:

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:18.04
    steps:
    - uses: ros-tooling/setup-ros@0.0.26
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install aws cli
      shell: bash
      run: |
        apt update;
        apt install -y software-properties-common awscli;
    - name: Tests aws cli
      shell: bash
      env:
        BUCKET_NAME: driving-sim/projects/maliput/packages/nightlies/
      run: |
        echo $PATH;
        ls -lash /usr/bin/aws;
        aws s3 ls ${BUCKET_NAME};

