name: ci-foxy image deploy

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  build_and_push:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'do-ci-foxy-image-build') || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and tag Docker image
      working-directory: ci_image/
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/ci_foxy_image:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/ci_foxy_image:latest
