name: manylinux-maliput image

on:
  workflow_dispatch:
    inputs:
      base_image:
        type: choice
        description: 'Base image for Docker build'
        required: false
        default: 'manylinux_2_28_x86_64'
        options:
          - 'manylinux2014_x86_64'
          - 'manylinux_2_28_x86_64'
      cp_python_version:
        type: choice
        description: 'Python version'
        required: false
        default: 'cp310-cp310'
        options:
          - 'cp38-cp38'
          - 'cp310-cp310'
  pull_request:
    types: [labeled]

jobs:
  build_and_push:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'do-manylinux-image-build') || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and tag Docker image
      working-directory: wheel_generation/
      run: |
        docker build \
          --build-arg BASE_IMAGE=quay.io/pypa/${{ github.event.inputs.base_image }} \
          --build-arg CP_PY_VERSION=${{ github.event.inputs.cp_python_version }} \
          -t ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.base_image }}_${{ github.event.inputs.cp_python_version }}_maliput:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.base_image }}_${{ github.event.inputs.cp_python_version }}_maliput:latest
